apiVersion: v2 #k8s helm version
name: catalogue
version: 0.0.1 # this is chart version
appVersion: 1.7.0 # this is application version
description: "Installing 1.7.0 version of catalogue microservice"
