name: feature-pipeline

on: workflow_dispatch

permissions:
    statuses: write
    contents: read

jobs:
    feature-pipeline:
        uses: ramu-cloud-labs/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main

        with:
            project: "roboshop"
            component: "catalogue"

        secrets: inherit
